### PR TITLE
Update package metadata.

### PR DESCRIPTION
**Pull request by timoxley**
Currently missing a few metadata fields.
Just ran `npm init -f` and tweaked a few things.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @timoxley! 

Were these breaking in some way for you? I'm down to add the `main` and maybe `scripts` (although for now it should point to the `Makefile`), but I prefer to omit all of the URL-related ones since they are noisy.

**Comment by timoxley** [comment]
messes with npmsearch.com

**Comment by ianstormtaylor** [comment]
How so? It seems like the link works?

**Comment by timoxley** [comment]
Links to GitHub rather than npm.

**Comment by ianstormtaylor** [comment]
Looks like most every package I search for on `npmsearch.com` links to GitHub instead of npm...?

**Comment by timoxley** [comment]
Heh ok perhaps it's a bug on npmsearch.

**Comment by evanbiederstedt** [comment]
Vote to close @ianstormtaylor

**Pull request closed without merging**
